openapi: "3.0.0"
info:
  version: 1.0.0
  title: User API
paths:
  /users:
    get:
      tags: [Users]
      operationId: ListUsers
      parameters:
        - name: limit
          in: query
          description: limit
          required: true
          schema:
            type: integer
            format: int32
        - name: page
          in: query
          description: page
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: user response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
    post:
      tags: [Users]
      operationId: CreateUsers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUser"
      responses:
        "200":
          description: user response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
components:
  schemas:
    user:
      allOf:
        - $ref: "#/components/schemas/NewUser"
        - required:
            - id
          properties:
            id:
              type: integer
              format: int64
    NewUser:
      required:
        - name
        - age
      properties:
        name:
          type: string
        age:
          type: number
