// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package openapi

// NewUser defines model for NewUser.
type NewUser struct {
	Age  float32 `json:"age"`
	Name string  `json:"name"`
}

// User defines model for user.
type User struct {
	Age  float32 `json:"age"`
	Id   int64   `json:"id"`
	Name string  `json:"name"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Limit limit
	Limit int32 `form:"limit" json:"limit"`

	// Page page
	Page int32 `form:"page" json:"page"`
}

// CreateUsersJSONRequestBody defines body for CreateUsers for application/json ContentType.
type CreateUsersJSONRequestBody = NewUser
