openapi: 3.0.0
info:
 title: Portfolio API
 version: 1.0.0

components:
 schemas:
   User:
     type: object
     properties:
       id:
         type: string
       email:
         type: string
       password:
         type: string
       created:
         type: string
         format: date-time
       updated:
         type: string
         format: date-time
       profile:
         $ref: '#/components/schemas/Profile'

   Profile:
     type: object
     properties:
       id:
         type: string
       userId:
         type: string
       name:
         type: string
       detail:
         type: string
       headerImage:
         type: string
       iconImage:
         type: string
       affiliation:
         type: string
       portfolios:
         type: array
         items:
           $ref: '#/components/schemas/Portfolio'
       like:
         type: array
         items:
           $ref: '#/components/schemas/Like'
       created:
         type: string
         format: date-time
       updated:
         type: string
         format: date-time

   Portfolio:
     type: object
     properties:
       id:
         type: string
       profileId:
         type: string
       profile:
         $ref: '#/components/schemas/Profile'
       title:
         type: string
       detail:
         type: string
       image:
         type: string
       like:
         type: array
         items:
           $ref: '#/components/schemas/Like'
       created:
         type: string
         format: date-time
       updated:
         type: string
         format: date-time

   Like:
     type: object
     properties:
       id:
         type: string
       profileId:
         type: string
       profile:
         $ref: '#/components/schemas/Profile'
       portfolioId:
         type: string
       portfolio:
         $ref: '#/components/schemas/Portfolio'
       created:
         type: string
         format: date-time

   UpdatePortfolioRequest:
     type: object
     properties:
       title:
         type: string
       image:
         type: string
       detail:
         type: string
     required:
       - title
       - image
       - detail

   CreatePortfolioRequest:
     type: object
     properties:
       portfolioId:
         type: string
       title:
         type: string
       image:
         type: string
       detail:
         type: string
     required:
       - portfolioId
       - title
       - image
       - detail

   ToggleLikeRequest:
     type: object
     properties:
       portfolioId:
         type: string
       profileId:
         type: string
     required:
       - portfolioId
       - profileId

paths:
 /api/portfolio/{portfolioId}:
   get:
     summary: Get a portfolio
     parameters:
       - name: portfolioId
         in: path
         required: true
         schema:
           type: string
     responses:
       '200':
         description: Successful response
         content:
           application/json:    
             schema:
               $ref: '#/components/schemas/Portfolio'

 /api/portfolio/{portfolioId}/update:
   post:
     summary: Update a portfolio
     parameters:
       - name: portfolioId
         in: path
         required: true
         schema:
           type: string
     requestBody:
       required: true
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/UpdatePortfolioRequest'
     responses:
       '200':
         description: Successful response
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Portfolio'

 /api/portfolio/create:
   post:
     summary: Create a portfolio
     requestBody:
       required: true
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/CreatePortfolioRequest'
     responses:
       '200':
         description: Successful response
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Portfolio'

 /api/portfolio/like:
   post:
     summary: toggle like a portfolio
     requestBody:
       required: true
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/CreatePortfolioRequest'
     responses:
       '200':
         description: Successful response
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/Portfolio'

/api/portfolio/like
/api/portfolios/
/api/profile/:userId
/api/profile/:userId/update
/api/auth/signup
/api/auth/signin
